### ISSUE TITLE
[Suggestion] add open computer or computer craft

### ISSUE THREAD

**Issue by taint19711** [Dark-Arcana/antimatter-chemistry#106]
Can you add the mod pack open computers or computer craft. So we can use it with DE mod pack please

**Comment by funniray** [comment]
I would also like to see OpenComputers or ComputerCraft

**Comment by mrlobaker** [comment]
Agree. For example, building NuclearCraft reactors with OpenComputers would be easier.

**Comment by MasterEnderman** [comment]
Wasn't added until now, won't be added in the future.
