### ISSUE TITLE
[Suggestion] Soda

### ISSUE THREAD

**Issue by TimelessRebornMC** [Dark-Arcana/antimatter-chemistry#111]
Add soda to Alchemistry in the pack since we already have things like caffeine. Speaking of caffeine, you might as well add coffee. Anyways, since soda needs syrup/carbonation/, maybe add a machine or two that can make drinks (so you can make soda/coffee in the same block) and can carbonate them if needed.

Credit to Soaryn for soda suggestion.

**Comment by MasterEnderman** [comment]
There will be no further updates to Alchemistry in 1.12.x -> closing
