### ISSUE TITLE
Attempting to make the Extra Cells universal wireless crafting crashes to desktop

### ISSUE THREAD

**Issue by Next-victim** [Dark-Arcana/antimatter-chemistry#113]
Attempting to take the normal wireless crafting terminal and combine it with a crafting terminal, which is the normal way to make the Universal Terminal with both Item and Crafting modes, crashes the game to desktop. all it takes is attempting to make the craft, it actually crashes before displaying the output item.

Crashlog: https://paste.ee/p/t57MH

On reloading the game and logging back into the server,  the crafting terminal was kicked back into my player inventory. This means it does lock players out when they do this.

**Comment by vektuz** [comment]
Looks like this is Extracells 2 issue 638 fyi https://github.com/ExtraCells/ExtraCells2/issues/638 

Doesn't look like Extracells2 will have it fixed for a while.

**Comment by MasterEnderman** [comment]
Seems to be fixed in the current Version of the pack (1.2.36)
