### ISSUE TITLE
Suggestion: Some other way to get draconium ingots

### ISSUE THREAD

**Issue by stormseeker71** [Dark-Arcana/antimatter-chemistry#152]
I strip mined for two hours and still don't have enough of the white crystals to make enough draconium to get started fusion crafting.  (I've got 4 fusion injectors so far)  I don't know if I'm mining at the wrong y-level (I tried 11 and 16) or if I'm just getting unlucky but the grind is becoming soul crushing.

**Comment by Next-victim** [comment]
The intent is to make an RF tools dimension of dimension infused ore via a material absorber and a silk touch pickaxe.

**Comment by stormseeker71** [comment]
Ah, well that still takes two stacks of ore.  So you might want to add a note on the quest that that is the intent because I would have never have thought of trying that myself, and I could have save the ore I had already found for that use.

**Comment by MasterEnderman** [comment]
after implementing #136 this should no longer be a problem
