### ISSUE TITLE
Super Laminar Flow Liquiducts lose fluid typing of all Nuclearcraft machines 

### ISSUE THREAD

**Issue by Next-victim** [Dark-Arcana/antimatter-chemistry#182]
This has happened a few times. 

We have a Fission Reactor set up with hydrogen-hydrogen as fuel. Recently, we found it running out of the secondary inventory of hydrogen. We then switched it to hydrogen-deuterium but it lost the connection to the deuterium a few days later.

We also had a reactor running Helium-3 and hydrogen, it lost the hydrogen so we switched it to He3-boron-11. It recently lost the boron-11.

After converting both setups to Hardened Fluiducts, they seem to be stable. been running for about 12 hours but will comment here if they break with the new ducting.

This has also happened with the @nuc electrolizers, they have gotten stuck pushing both oxygen and hydrogen on us in the past few days. We had chalked it up to lag and loading/unloading the area but they now seem stable on Xnet Advanced Connectors.

This must have happened in a recent nuclearcraft update, as this wasn't an issue about 3 week ago.

**Comment by nuc** [comment]
I swear, I don't possess any electrolizers.

**Comment by Next-victim** [comment]
After further inspection and careful observation: the issue has changed slightly. It appears that fluids will rarely randomly change to a few mB of hydrogen. Proven by attaching retrievers to the affected lines with H as the whitelisted item. It does seem to be Super Laminar Flow ducts mostly, but we had an issue with hardened ducts too in the past week. Will try adding more configurations to the NC machines to see if the new sided-ness fixes it.

**Comment by Next-victim** [comment]
Example of a line with the protection tank that has protected a 22 size fusion reactor:
![2019-09-04_01 05 21](https://user-images.githubusercontent.com/51034324/64227111-2ca3a980-ceb0-11e9-8ed6-b65d6ffa4e54.png)

**Comment by Cyprex** [comment]
Do these ducts store fluids or do they transfer instantly? Trying to rule out that 1 pipe got contaminated once
