### ISSUE TITLE
80x Potassium Chloride Quest

### ISSUE THREAD

**Issue by memematron** [Dark-Arcana/antimatter-chemistry#194]
Mine is stuck on 75/80 and no matter how many more i collect the progress remains the same. I really like this modpack but now im stuck and cant do anything

**Comment by al132mc** [comment]
This happens sometimes. Try just opening a chest and this should re-sync your quest so it completes properly.

**Comment by memematron** [comment]
That doesn’t seem to work, ive been opening chests all the time and it hasnt helped

**Comment by al132mc** [comment]
That's odd.. what version of the pack are you playing? Also, please double check that it's actually potassium chloride that you have and not some other compound.

**Comment by Militis** [comment]
I know this is a year old, but I had this problem yesterday. If you have the items in a drawer, it doesn't seem to count them. Pull them all out of the drawer and into your inventory.
