### ISSUE TITLE
Quest Book gets increasingly laggy as players complete more quests, especially after beginning Chapter 4

### ISSUE THREAD

**Issue by ghost** [Dark-Arcana/antimatter-chemistry#27]

**Comment by al132mc** [comment]
A hacky, confirmed workaround for this is to go into edit mode by typing '/ftbquests editing_mode' and start unlinking som quest dependencies for quests you've already completed. Obviously this is not ideal, especially on servers where people are at different stages of progress.

**Comment by al132mc** [comment]
tangentially related to https://github.com/FTBTeam/FTB-Quests/issues/226

**Comment by al132mc** [comment]
A few versions ago I unlinked the start of chapters from the end of the previous chapter. It's not ideal, but it should prevent users from experiencing this issue.

**Comment by MasterEnderman** [comment]
"fixed" ages ago but the issue was never closed
