### ISSUE TITLE
Suggested low-impact cosmetic mods

### ISSUE THREAD

**Issue by myleszey** [Dark-Arcana/antimatter-chemistry#34]
The pack is currently lacking in aesthetic design capability (though that's obviously not the focus, it could still use something more than the vanilla architecture). A couple things that fit well with the theming here could include ZTones or Quark without changing anything about the progression.

**Comment by al132mc** [comment]
Indeed, I agree that it's lacking in aesthetic content, though my primary concern about adding mods like Chisel or ZTones is that loading time/RAM usage are very high prorities of mine, so if I do add cosmetic mods I would likely add smaller ones. I will have to look around to see if I can find anything interesting.

**Comment by daan7008** [comment]
@al132mc he found some mods and these are them: Nifty, ElementMod, and Plated

**Comment by myleszey** [comment]
specifically [NiftyBlocks](https://minecraft.curseforge.com/projects/niftyblocks?gameCategorySlug=mc-mods&projectID=228189), [ElementMod](https://minecraft.curseforge.com/projects/elementmod?gameCategorySlug=mc-mods&projectID=266647), and [Plated](https://minecraft.curseforge.com/projects/plated?gameCategorySlug=mc-mods&projectID=300647).
There also exists a mod simply titled Nifty that only adds stair and fence equivalents of vanilla blocks.

**Comment by al132mc** [comment]
I've added a few cosmetic mods in 1.1.1. but I will leave this issue open as I would be open to adding more.

**Comment by BaalSalmon** [comment]
Perhaps [Chisel](https://minecraft.curseforge.com/projects/chisel) to make the antimatter world more... varied?

**Comment by MasterEnderman** [comment]
As the modpack is basically finished there won't be any additions of new content mods.
