### ISSUE TITLE
Spawner with pink slime crash server

### ISSUE THREAD

**Issue by yarkylz** [Dark-Arcana/antimatter-chemistry#43]
If you put syringe with essence of Pink Slime from Industrial Foregoing into spawner from RFTools you crash server ;-)

**Comment by al132mc** [comment]
Okay, thanks for letting me know. My advice is uh, don't do it again, lol

**Comment by al132mc** [comment]
Also, sorry I forgot to ask. Could you please attach the crash log in a pastebin or something similar?

**Comment by yarkylz** [comment]
Oh, sorry. https://pastebin.com/JJanAv1m
