### ISSUE TITLE
Unable to open Sarcophagus after beating Pharaoh

### ISSUE THREAD

**Issue by Next-victim** [Dark-Arcana/antimatter-chemistry#57]
After beating a Pharaoh, I've been unable to open the sarcophagus. It moves a tiny bit then shuts. I also can't break the thing either. Pick is 

Steel Pickaxe
slime binding
steel head
experience metal binding
Fortified with Obsidian 
Diamond added
Luck 3

Photo of what it looks like right before it shuts:
![2019-05-30_23 11 56](https://user-images.githubusercontent.com/51034324/58679398-3fe32e00-8331-11e9-809e-a3278e551192.png)

Attempting with a Diamond Pickaxe: Same issue, it's unbreakable. image below:
![2019-05-30_23 28 32](https://user-images.githubusercontent.com/51034324/58679710-bd5b6e00-8332-11e9-9979-1e676b4a31e5.png)

**Comment by Next-victim** [comment]
Just a small note: using a Stone Pickaxe doesn't resolve it
![2019-06-01_04 09 29](https://user-images.githubusercontent.com/51034324/58745775-320dd580-8423-11e9-9cfc-7b81acff8690.png)

**Comment by Next-victim** [comment]
Also, I can't mine the traps and they say the same "[red X] Pickaxe (Level Stone)". Nothing else in Atum seems to do that besides the sarcophagus and the traps. The other wall blocks simply say "no tool".

**Comment by Next-victim** [comment]
Image of the MCEdit data from the Sarcophagus. Note that the NTB tag "Lock" doesn't have a state, could that be the problem? 
![aTUM ntb DATA](https://user-images.githubusercontent.com/51034324/58746208-9469d480-8429-11e9-9002-20ef5a67c4c7.PNG)

**Comment by Next-victim** [comment]
Marking both sides of the Sarcophagus with the "openable" tag to "1" make it open and displays items correctly. Might be a disconnect of the sarcophagus detecting the pharaoh died.

Will attempt a second pyramid to see if it will happen again.

**Comment by Next-victim** [comment]
Issue didn't occur when I went to the second Pyramid. Also didn't occur after putting the pharaoh in a piggy Backpack before killing. Not quite sure what happened differently the first time.

**Comment by al132mc** [comment]
I finally got around to testing this today, and it looks fine for me. I guess i'll assume that an Atum update fixed it? Re-open this issue if it happens again

![2019-06-10_10 21 15](https://user-images.githubusercontent.com/39097092/59205958-8de60600-8b69-11e9-99fd-22e0390d11b6.png)

**Comment by Next-victim** [comment]
User PeachizXD on the server is having this issue.

Video they posted: https://cdn.discordapp.com/attachments/458703035997224975/587999744828243988/video.mov

**Comment by Next-victim** [comment]
After talking to PeachizXD more, it seems like summoning the pharaoh, then leaving Atum and coming back, then killing the pharaoh causes the issue.

They had died before getting the pharaoh kill. Not sure if they /home back or used some other way.

**Comment by GirafiStudios** [comment]
What mod are you using for /home?

**Comment by al132mc** [comment]
FTB Utils, though I anticipate it doesn't matter, it's most likely a matter of chunkloading or something of the sort

**Comment by TopPercentageRattata** [comment]
I had a similar issue. Someone else had summoned a Pharoah, they died and never went back there, then I killed the pharaoh but the sarcophagus was all glitchy. I could open it but only for a split second, and if I spammed rmb on it i could see all the items in it for a bit, but couldn't break it or open it normally, probably because I wasn't the one who summoned it. Possibly intended that I couldn't open it bc not the summoner but the inventory being all glitchy and opening for split second probably not intended

**Comment by GirafiStudios** [comment]
If any of you guys have any more information, that have not already been mentioned here, please let me know in https://github.com/TeamMetallurgy/Atum2/issues/137 :)

**Comment by Next-victim** [comment]
Discovery! A player (or server mod) in gamemode Creative, can physically break the sarcophagus and the items will drop. Not a fix but a way around losing the items.

**Comment by Meldexun** [comment]
I have the same issue. It always occurs once the chunk of the pharaoh and his sarcophagus is unloaded. So for example:
1. You summon a pharaoh
2. Exit the world to the main menu (chunks get unloaded)
3. Rejoin the world
4. Kill the pharaoh
5. Sarcophagus is bugged and can't be opened

**Comment by MasterEnderman** [comment]
The original Bug was fixed 2019-08-30. This should no longer be a problem.
