### ISSUE TITLE
Themal dynamics cables don't works with nuclearcrafts machines

### ISSUE THREAD

**Issue by Redmod82** [Dark-Arcana/antimatter-chemistry#59]
Version : 1.2.4
after doing the update (1.1.1 to 1.2.4), all of my NC (nuclear craft) machines don't works with thermals cables ( RF, item.....)

**Comment by al132mc** [comment]
Well that's odd...could you try breaking the machines and placing them again?

**Comment by Redmod82** [comment]
It worked ! Thank you so much

**Comment by Redmod82** [comment]
It works but the bug comes back each time the server is restarted

**Comment by al132mc** [comment]
Could you try using extra utils cables to help narrow down if this is a nuclearcraft problem or a thermal problem?

**Comment by Redmod82** [comment]
I just used extrautilities for Item/fluid and draconic crystals for energy and it works

**Comment by al132mc** [comment]
Very strange

**Comment by MasterEnderman** [comment]
Doesn't seem to be a problem in the latest version (1.2.36)
