### ISSUE TITLE
Crash on creation of fluid nodes from Extra Utilities

### ISSUE THREAD

**Issue by Next-victim** [Dark-Arcana/antimatter-chemistry#73]
Credit to Discord user "Finola Wren"

Player attempted to create Fluid Nodes from Extra Utilities and game crashed on assembling recipe in the a Tinker's Construct crafting bench with a double chest inventory attached. They also said that they shift-clicked items in from both the double chest AND their player inventory.

Player's crash log is here:
http://dpaste.com/1TZ9M7Z

When trouble shooting, they attempted to reload without changes and had a repeat crash. 

After talking to the Discord group, They attempted to change their video setting from " fast" back to the default of "fancy".This allowed them to get into their world and break the crafting table. 

Issue appears to have resolved with that change.

**Comment by MasterEnderman** [comment]
Probably related to #161
